// End-to-End-API-Test gegen eine LEERE Datenbank.
// Start: Server lokal starten (npm run local), dann: node scripts/api-test.mjs
const BASE = 'http://localhost:8888/api';
let cookie = '';
let fails = 0;
const ok = (cond, msg) => { if (cond) console.log('  ✓', msg); else { fails++; console.log('  ✗', msg); } };
async function call(method, path, body, { csrf = true, form = false, raw = false, useCookie = true } = {}) {
  const headers = {};
  if (csrf) headers['X-Requested-With'] = 'crm';
  if (body && !form) headers['Content-Type'] = 'application/json';
  if (useCookie && cookie) headers.cookie = cookie;
  const res = await fetch(BASE + path, { method, headers, body: body ? (form ? body : JSON.stringify(body)) : undefined });
  const sc = res.headers.get('set-cookie');
  if (sc && useCookie) cookie = sc.split(';')[0];
  if (raw) return res;
  const data = await res.json().catch(() => null);
  return { status: res.status, data };
}

console.log('Auth');
let r = await call('GET', '/auth/status');
ok(r.data.needsSetup === true, 'Setup nötig bei leerer DB');
r = await call('GET', '/creators');
ok(r.status === 401, 'Geschützte Route ohne Login → 401');
r = await call('POST', '/auth/setup', { name: 'Admin', email: 'admin@test.de', password: 'kurz' });
ok(r.status === 422, 'Zu kurzes Passwort abgelehnt');
r = await call('POST', '/auth/setup', { name: 'Admin', email: 'admin@test.de', password: 'sicher1234' }, { csrf: false });
ok(r.status === 403, 'CSRF-Header fehlt → 403');
r = await call('POST', '/auth/setup', { name: 'David Admin', email: 'Admin@Test.de', password: 'sicher1234', demo: false });
ok(r.status === 200 && r.data.user.role === 'admin', 'Ersteinrichtung legt Admin an');
r = await call('POST', '/auth/setup', { name: 'X', email: 'x@test.de', password: 'sicher1234' });
ok(r.status === 409, 'Zweites Setup verhindert');
cookie = '';
r = await call('POST', '/auth/login', { email: 'admin@test.de', password: 'falsch123' });
ok(r.status === 401, 'Falsches Passwort → 401');
r = await call('POST', '/auth/login', { email: 'ADMIN@test.de', password: 'sicher1234' });
ok(r.status === 200, 'Login (E-Mail case-insensitiv)');

console.log('Benutzer');
r = await call('POST', '/users', { name: 'Max Mustermann', email: 'max@test.de', password: 'passwort123', role: 'manager' });
ok(r.status === 200, 'Admin legt Manager an');
const maxId = r.data.user.id;
r = await call('POST', '/users', { name: 'Dup', email: 'max@test.de', password: 'passwort123' });
ok(r.status === 409, 'Doppelte E-Mail abgelehnt');

console.log('Tags');
r = await call('POST', '/tags', { name: 'Fashion', color: 'pink' });
const tFashion = r.data.tag.id;
r = await call('POST', '/tags', { name: 'Premium', color: 'amber' });
const tPremium = r.data.tag.id;
r = await call('POST', '/tags', { name: 'fashion' });
ok(r.status === 409, 'Tag-Duplikat (case-insensitiv) abgelehnt');

console.log('Creator CRUD + Validierung');
r = await call('POST', '/creators', { display_name: '' });
ok(r.status === 422 && r.data.details.display_name, 'Pflichtfeld Name');
r = await call('POST', '/creators', { display_name: 'X', email: 'kaputt' });
ok(r.status === 422 && r.data.details.email, 'Ungültige E-Mail');
r = await call('POST', '/creators', { display_name: 'X', instagram: { username: 'x', followers: -5 } });
ok(r.status === 422, 'Negative Follower abgelehnt: ' + r.data.error);
r = await call('POST', '/creators', { display_name: 'X', tiktok: { url: 'kein url' } });
ok(r.status === 422, 'Ungültige URL abgelehnt: ' + r.data.error);
r = await call('POST', '/creators', {
  display_name: 'Anna Müller', email: 'anna@example.com', city: 'Berlin', region: 'Berlin', country: 'Deutschland', niche: 'Fashion / Lifestyle',
  instagram: { username: '@anna', followers: 125000, engagement_rate: '4,2' }, tiktok: { username: 'https://www.tiktok.com/@annamueller', followers: 280000 },
  tag_ids: [tFashion, tPremium], manager_id: maxId, status: 'Aktiv',
});
ok(r.status === 201, 'Creator angelegt');
const anna = r.data.creator.id;
r = await call('POST', '/creators', { display_name: 'Tom Big', country: 'Deutschland', instagram: { username: 'tombig', followers: 150000 } });
const tom = r.data.creator.id;
await call('POST', '/creators', { display_name: 'Lisa Small', country: 'Deutschland', instagram: { username: 'lisa', followers: 20000 } });
await call('POST', '/creators', { display_name: 'Wien Big', country: 'Österreich', instagram: { username: 'wien', followers: 300000 } });
r = await call('GET', `/creators/${anna}`);
ok(r.data.socials.instagram.username === 'anna' && r.data.socials.instagram.url === 'https://www.instagram.com/anna/', 'Username normalisiert + URL generiert');
ok(r.data.socials.tiktok.username === 'annamueller', 'TikTok-Username aus URL extrahiert');
ok(r.data.socials.instagram.engagement_rate === 4.2, 'Engagement Rate mit Komma');
ok(r.data.tags.length === 2 && r.data.creator.manager_name === 'Max Mustermann', 'Tags & Manager verknüpft');

console.log('Suche & Filter');
r = await call('GET', '/creators?country=Deutschland&followers_platform=instagram&min_followers=100001&contacted=no');
ok(r.data.total === 2 && r.data.items.every((c) => c.instagram_followers > 100000), 'Beispiel: DE, >100k IG, nicht angeschrieben → ' + r.data.items.map((c) => c.display_name).join(', '));
r = await call('GET', '/creators?q=@annamueller');
ok(r.data.total === 1, 'Suche nach TikTok-Username');
r = await call('GET', `/creators?tags=${tFashion},${tPremium}`);
ok(r.data.total === 1, 'Tag-Filter');
r = await call('GET', '/creators?sort=followers&dir=desc');
ok(r.data.items[0].display_name === 'Wien Big', 'Sortierung nach Followern');
r = await call('GET', '/creators?sort=name&dir=asc&page_size=2&page=2');
ok(r.data.items.length === 2 && r.data.pages === 2, 'Pagination');

console.log('Bearbeiten & Aktivitäten');
r = await call('PATCH', `/creators/${tom}`, { status: 'Kontakt aufgenommen', city: 'Hamburg' });
ok(r.status === 200, 'Creator bearbeitet');
r = await call('GET', `/creators/${tom}/activities`);
ok(r.data.items.some((a) => a.message.includes("von 'Lead' auf 'Kontakt aufgenommen'")), 'Statusänderung protokolliert');
const before = r.data.items.length;
r = await call('GET', `/creators/${tom}`);
await call('PATCH', `/creators/${tom}`, { instagram: { username: 'tombig', followers: 150000 }, tag_ids: [] });
r = await call('GET', `/creators/${tom}/activities`);
ok(r.data.items.length === before, 'Unveränderte Social-/Tag-Daten erzeugen keinen Log-Eintrag');

console.log('Outreach & Follow-ups');
const today = new Date().toLocaleDateString('sv-SE', { timeZone: 'Europe/Berlin' });
r = await call('POST', '/outreach', { creator_id: tom, channel: 'Instagram DM', subject: 'Erstkontakt', result: 'Erstkontakt', follow_up_date: '2020-01-01' });
ok(r.status === 201, 'Kontakt erfasst');
r = await call('GET', `/creators/${tom}`);
ok(r.data.creator.contacted === true && r.data.creator.outreach_status === 'Kontaktiert', 'Automatisch angeschrieben + Status Kontaktiert');
r = await call('GET', '/followups?range=overdue');
ok(r.data.items.length === 1, 'Überfälliges Follow-up erscheint');
r = await call('POST', '/outreach', { creator_id: tom, channel: 'E-Mail', result: 'Antwort erhalten', outreach_status: 'Antwort erhalten', follow_up_date: today });
r = await call('GET', '/followups?range=overdue');
ok(r.data.items.length === 0, 'Neuer Kontakt schließt alte Follow-ups');
r = await call('GET', '/followups?range=today');
ok(r.data.items.length === 1, 'Follow-up heute');
r = await call('GET', '/outreach?creator_id=' + tom);
ok(r.data.items.length === 2 && new Date(r.data.items[0].occurred_at) >= new Date(r.data.items[1].occurred_at), 'Kontaktverlauf chronologisch');

console.log('Kooperationen & Finanzen');
r = await call('POST', '/collaborations', { creator_id: anna, brand: 'Brand A', start_date: '2026-03-01', end_date: '2026-02-01' });
ok(r.status === 422, 'Enddatum vor Start abgelehnt');
for (const [fee, status] of [[2000, 'Abgeschlossen'], [3500, 'Aktiv'], [1500, 'Geplant'], [999, 'Anfrage'], [500, 'Abgebrochen']]) {
  r = await call('POST', '/collaborations', { creator_id: anna, brand: 'Brand ' + fee, fee, status, start_date: today });
}
ok(r.status === 201, 'Kooperationen angelegt');
r = await call('GET', `/collaborations?creator_id=${anna}&status=Aktiv`);
const collabId = r.data.items[0].id;
r = await call('GET', `/creators/${anna}`);
ok(r.data.stats.total_revenue === 7000, 'Gesamtumsatz = 7.000 € (nur bestätigte Kooperationen): ' + r.data.stats.total_revenue);
ok(r.data.stats.active_collabs === 1, 'Aktive Kooperationen gezählt');
r = await call('PATCH', `/collaborations/${collabId}`, { invoice_status: 'Bezahlt' });
ok(r.status === 200, 'Rechnungsstatus geändert');
r = await call('GET', '/finance/summary');
ok(r.data.totals.volume === 7000 && r.data.totals.agency_total === 1400 && r.data.totals.total === 1400 && r.data.totals.month === 1400 && r.data.totals.paid === 3500, 'Finanzübersicht: Volumen 7.000 €, Provision 20 % = 1.400 €, bezahlt 3.500 €');
r = await call('GET', `/collaborations?creator_id=${anna}&timeframe=past`);
ok(r.data.items.length === 2, 'Vergangene Kooperationen (abgeschlossen/abgebrochen)');

console.log('Aufgaben');
r = await call('POST', '/tasks', { title: 'Briefing senden', creator_id: anna, collaboration_id: collabId, due_date: today, priority: 'Hoch' });
ok(r.status === 201, 'Aufgabe erstellt');
const taskId = r.data.id;
r = await call('POST', '/tasks', { title: 'Falsch', creator_id: tom, collaboration_id: collabId });
ok(r.status === 422, 'Kooperation eines anderen Creators abgelehnt');
r = await call('GET', '/tasks?due=today&status=open');
ok(r.data.items.length === 1, 'Filter heute fällig');
r = await call('PATCH', `/tasks/${taskId}`, { status: 'Erledigt' });
r = await call('GET', `/tasks/${taskId}`);
ok(r.data.task.completed_at, 'Abschlussdatum gesetzt');

console.log('Verträge & Dokumente');
r = await call('PUT', `/creators/${anna}/contract`, { status: 'Aktiv', start_date: today, end_date: '2027-12-31', exclusivity: 'Fashion' });
ok(r.status === 200 && r.data.contract.status === 'Aktiv', 'Vertrag gespeichert');
r = await call('GET', '/creators?has_contract=yes');
ok(r.data.total === 1, 'Filter Vertrag vorhanden');
const pdf = new Blob([Buffer.from('%PDF-1.4\n1 0 obj<<>>endobj\ntrailer<<>>\n%%EOF')], { type: 'application/pdf' });
let fd = new FormData();
let res;
fd.append('file', pdf, 'Vertrag Anna.pdf'); fd.append('creator_id', String(anna)); fd.append('category', 'Verträge');
r = await call('POST', '/documents', fd, { form: true });
ok(r.status === 201, 'PDF hochgeladen');
const docId = r.data.id;
fd = new FormData();
fd.append('file', new Blob(['<script>alert(1)</script>']), 'boese.pdf'); fd.append('creator_id', String(anna)); fd.append('category', 'Verträge');
r = await call('POST', '/documents', fd, { form: true });
ok(r.status === 415, 'Getarnte Datei abgelehnt');
fd = new FormData();
fd.append('file', new Blob(['x']), 'a.exe'); fd.append('creator_id', String(anna)); fd.append('category', 'Verträge');
r = await call('POST', '/documents', fd, { form: true });
ok(r.status === 415, '.exe abgelehnt');
res = await call('GET', `/documents/${docId}/file?download=1`, null, { raw: true });
const txt = await res.text();
ok(res.status === 200 && txt.startsWith('%PDF') && res.headers.get('content-disposition').startsWith('attachment'), 'Download funktioniert');
r = await call('GET', `/creators/${anna}/activities`);
ok(r.data.items.some((a) => a.action === 'contract_uploaded'), 'Upload in Historie');
const png = Buffer.from('89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4890000000d49444154789c6300010000050001', 'hex');
fd = new FormData(); fd.append('file', new Blob([png]), 'a.png');
r = await call('POST', `/creators/${anna}/avatar`, fd, { form: true });
ok(r.status === 200 && r.data.avatar_url, 'Profilbild hochgeladen');
res = await call('GET', r.data.avatar_url.replace('/api', ''), null, { raw: true });
ok(res.status === 200 && res.headers.get('content-type') === 'image/png', 'Profilbild ausgeliefert');

console.log('Dashboard & globale Suche');
r = await call('GET', '/dashboard');
ok(r.status === 200 && r.data.kpi.creators_total === 4 && r.data.kpi.contracts_active === 1, 'Dashboard-KPIs');
ok(r.data.followups.length === 1 && r.data.activities.length > 5, 'Dashboard Follow-ups & Aktivitäten');
r = await call('GET', '/search?q=brand 35');
ok(r.data.collaborations.length === 1, 'Globale Suche findet Brand');
r = await call('GET', '/search?q=briefing');
ok(r.data.tasks.length === 1, 'Globale Suche findet Aufgabe');
r = await call('GET', '/search?q=@annamueller');
ok(r.data.creators.length === 1, 'Globale Suche findet TikTok-Username');

console.log('Rechte');
const adminC = cookie;
cookie = '';
await call('POST', '/auth/login', { email: 'max@test.de', password: 'passwort123' });
r = await call('GET', `/creators/${anna}`);
ok(r.status === 200, 'Manager sieht alle Creator');
r = await call('PATCH', `/creators/${tom}`, { niche: 'Gaming' });
ok(r.status === 200, 'Manager darf bearbeiten');
r = await call('POST', '/users', { name: 'Hacker', email: 'h@test.de', password: 'passwort123' });
ok(r.status === 403, 'Manager darf keine Benutzer anlegen');
r = await call('DELETE', `/creators/${tom}`);
ok(r.status === 403, 'Manager darf nicht endgültig löschen');
const maxCookie = cookie;
cookie = adminC;
r = await call('PATCH', `/users/${maxId}`, { is_active: false });
ok(r.status === 200, 'Admin deaktiviert Manager');
cookie = maxCookie;
r = await call('GET', '/creators');
ok(r.status === 401, 'Bestehende Sitzung des deaktivierten Benutzers ungültig');
cookie = '';
r = await call('POST', '/auth/login', { email: 'max@test.de', password: 'passwort123' });
ok(r.status === 403, 'Deaktivierter Benutzer kann sich nicht anmelden');
cookie = adminC;
r = await call('GET', '/creators', null, { raw: true });
ok(r.status === 200, 'Admin-Sitzung weiterhin gültig');

console.log('Creator-Bereich');
cookie = adminC;
r = await call('POST', `/creators/${tom}/portal`, { email: 'kaputt' });
ok(r.status === 422, 'Ungültige Login-E-Mail abgelehnt');
r = await call('POST', `/creators/${tom}/portal`, { email: 'Tom@Creator.de', send_mail: false });
ok(r.status === 200 && r.data.link.includes('/einladung?token=') && r.data.access.invite_pending, 'Zugang angelegt, Einladungslink erzeugt');
const inviteToken = new URL(r.data.link, 'http://x').searchParams.get('token');
r = await call('GET', '/users');
ok(!r.data.users.some((u) => u.role === 'creator'), 'Creator-Konten tauchen nicht in der Team-Liste auf');
cookie = '';
r = await call('GET', `/auth/invite?token=${inviteToken}`);
ok(r.data.valid === true && r.data.email === 'tom@creator.de', 'Einladung gültig');
r = await call('GET', `/auth/invite?token=falsch`);
ok(r.data.valid === false, 'Falscher Token ungültig');
r = await call('POST', '/auth/invite', { token: inviteToken, password: 'kurz' });
ok(r.status === 422, 'Zu kurzes Passwort bei Einladung abgelehnt');
r = await call('POST', '/auth/invite', { token: inviteToken, password: 'creator-pass-1' });
ok(r.status === 200 && r.data.user.role === 'creator' && r.data.user.creator_id === tom, 'Einladung angenommen, eingeloggt');
const creatorC = cookie;
r = await call('POST', '/auth/invite', { token: inviteToken, password: 'creator-pass-2' });
ok(r.status === 410, 'Einladungslink nur einmal nutzbar');
cookie = creatorC;
for (const path of ['/creators', '/users', '/dashboard', '/collaborations', '/finance/summary', '/documents', '/tasks', `/creators/${tom}`, '/settings', '/search?q=to']) {
  r = await call('GET', path);
  ok(r.status === 403, `Creator gesperrt: GET ${path}`);
}
r = await call('POST', '/creators', { display_name: 'Hack' });
ok(r.status === 403, 'Creator darf keine Creator anlegen');
r = await call('GET', '/portal/overview');
ok(r.status === 200 && r.data.creator.id === tom, 'Creator sieht eigene Übersicht');
r = await call('PATCH', '/auth/me', { digest_enabled: true });
ok(r.status === 200 && r.data.user.digest_enabled === false, 'Creator kann Team-Mail nicht aktivieren');
for (const path of ['/guides', '/guides/werbekennzeichnung', '/guides/werbekennzeichnung/pdf', '/lists']) {
  r = await call('GET', path);
  ok(r.status === 403, `Creator gesperrt: GET ${path}`);
}

cookie = adminC;
r = await call('GET', '/guides');
ok(r.status === 200 && r.data.items.length >= 20, 'Team sieht alle Leitfäden');
r = await call('POST', '/collaborations', { creator_id: tom, brand: 'Portal Brand', fee: 1000, commission_rate: 20, status: 'Aktiv', start_date: today, deadline: today, notes: 'GEHEIM-INTERN',
  contact_name: 'Lisa Marke', contact_email: 'lisa@brand.de', usage_rights: '6 Monate organisch', exclusivity: '4 Wochen Kategorie Getränke', briefing_date: today, publish_date: today, invoice_due_date: today });
ok(r.status === 200 || r.status === 201, 'Kooperation mit neuen Deal-Feldern angelegt');
const pColl = r.data.id;
r = await call('POST', '/collaborations', { creator_id: anna, brand: 'Fremd Brand', fee: 500, status: 'Aktiv', start_date: today });
const foreignColl = r.data.id;
fd = new FormData();
fd.append('file', pdf, 'Briefing Tom.pdf'); fd.append('creator_id', String(tom)); fd.append('category', 'Briefings'); fd.append('collaboration_id', String(pColl));
r = await call('POST', '/documents', fd, { form: true });
const tomDoc = r.data.id;

cookie = creatorC;
r = await call('GET', '/portal/collaborations?filter=active');
const pc = r.data.items.find((x) => x.id === pColl);
ok(pc && pc.money.net === 800 && pc.money.agency_fee === 200 && pc.money.vat === 152 && pc.stage === 'Content fällig', 'Creator sieht Honorar, Provision, USt und Stufe');
ok(pc && pc.contact_name === 'Lisa Marke' && pc.usage_rights && pc.exclusivity, 'Ansprechpartner, Nutzungsrechte, Exklusivität sichtbar');
ok(r.data.items.every((x) => x.id !== foreignColl), 'Fremde Kooperationen unsichtbar');
ok(!JSON.stringify(r.data).includes('GEHEIM-INTERN'), 'Interne Notizen bleiben verborgen');
r = await call('GET', '/portal/documents');
const docCount = (d) => d.groups.reduce((a, g) => a + g.items.length, 0);
ok(docCount(r.data) === 0, 'Nicht freigegebene Datei unsichtbar');
res = await call('GET', `/portal/documents/${tomDoc}/file`, null, { raw: true });
ok(res.status === 404, 'Nicht freigegebene Datei nicht abrufbar');
cookie = adminC;
r = await call('PATCH', `/documents/${tomDoc}`, { visible_to_creator: true });
ok(r.status === 200, 'Team gibt Datei frei');
cookie = creatorC;
r = await call('GET', '/portal/documents');
ok(docCount(r.data) === 1 && r.data.groups.find((g) => g.key === 'briefing').items.length === 1, 'Freigegebene Datei sichtbar (Gruppe Briefings)');
res = await call('GET', `/portal/documents/${tomDoc}/file`, null, { raw: true });
ok(res.status === 200, 'Freigegebene Datei abrufbar');
res = await call('GET', `/portal/documents/${docId}/file`, null, { raw: true });
ok(res.status === 404, 'Datei eines anderen Creators nicht abrufbar');
fd = new FormData();
fd.append('file', pdf, 'Rechnung Tom.pdf'); fd.append('category', 'Verträge');
r = await call('POST', '/portal/documents', fd, { form: true });
ok(r.status === 422, 'Creator darf nur Rechnungen/Sonstiges hochladen');
fd = new FormData();
fd.append('file', pdf, 'Rechnung Tom.pdf'); fd.append('category', 'Rechnungen'); fd.append('collaboration_id', String(foreignColl));
r = await call('POST', '/portal/documents', fd, { form: true });
ok(r.status === 422, 'Upload zu fremder Kooperation abgelehnt');
fd = new FormData();
fd.append('file', pdf, 'Rechnung Tom.pdf'); fd.append('category', 'Rechnungen'); fd.append('collaboration_id', String(pColl));
r = await call('POST', '/portal/documents', fd, { form: true });
ok(r.status === 201, 'Creator lädt Rechnung hoch');
r = await call('POST', `/portal/collaborations/${pColl}/content`, { content_links: 'kein link' });
ok(r.status === 422, 'Ungültiger Content-Link abgelehnt');
r = await call('POST', `/portal/collaborations/${foreignColl}/content`, { content_links: 'https://example.com/a' });
ok(r.status === 404, 'Content für fremde Kooperation abgelehnt');
r = await call('POST', `/portal/collaborations/${pColl}/content`, { content_links: 'https://drive.example.com/reel1\nhttps://drive.example.com/story', content_note: 'Bitte prüfen' });
ok(r.status === 200 && r.data.item.status === 'Abnahme', 'Content eingereicht → Status „Abnahme“');
const yr = today.slice(0, 4);
r = await call('GET', `/portal/finance?year=${yr}`);
ok(r.status === 200 && r.data.income.expected.net === 800 && r.data.agency_fee === 200 && r.data.months.length === 12, 'Finanzen: erwartet + Provision');

// Nachrichten am Deal
r = await call('POST', `/portal/collaborations/${pColl}/messages`, { body: 'Kann ich die Story einen Tag später posten?' });
ok(r.status === 201, 'Creator schreibt Nachricht am Deal');
r = await call('POST', `/portal/collaborations/${foreignColl}/messages`, { body: 'hack' });
ok(r.status === 404, 'Nachricht an fremden Deal abgelehnt');
r = await call('GET', `/portal/collaborations/${pColl}`);
ok(r.status === 200 && r.data.messages.length === 1 && r.data.messages[0].mine === true && r.data.documents.length === 2, 'Deal-Detail mit Nachrichten und Dokumenten');
r = await call('GET', `/portal/collaborations/${foreignColl}`);
ok(r.status === 404, 'Fremdes Deal-Detail gesperrt');

// Kalender
r = await call('POST', '/portal/calendar', { entry_date: today, title: 'Reel drehen', kind: 'Content-Plan', platform: 'instagram', entry_time: '14:30' });
ok(r.status === 201, 'Eigener Kalendereintrag');
const entryId = r.data.id;
r = await call('POST', '/portal/calendar', { entry_date: today, title: 'x', entry_time: '25 Uhr' });
ok(r.status === 422, 'Ungültige Uhrzeit abgelehnt');
r = await call('GET', `/portal/calendar?from=${today}&to=${today}`);
const kinds = new Set(r.data.events.map((e) => e.kind));
ok(['Briefing', 'Content-Abgabe', 'Veröffentlichung', 'Zahlung', 'Content-Plan'].every((k) => kinds.has(k)), 'Kalender: Deal-Termine + eigene Einträge');
r = await call('PATCH', `/portal/calendar/${entryId}`, { done: true });
ok(r.status === 200, 'Kalendereintrag abgehakt');

// Ausgaben & Erstattung
r = await call('POST', '/portal/expenses', { expense_date: today, title: 'Ringlicht', category: 'Technik & Equipment', amount_gross: 119, vat_rate: 19 });
ok(r.status === 201, 'Ausgabe erfasst');
const expId = r.data.id;
r = await call('POST', '/portal/expenses', { expense_date: today, title: 'Bahnticket Shooting', category: 'Reise & Fahrtkosten', amount_gross: 50, vat_rate: 7, reimbursable: true, collaboration_id: pColl });
ok(r.status === 201, 'Auslagenerstattung beantragt');
const reimbId = r.data.id;
r = await call('POST', '/portal/expenses', { expense_date: today, title: 'x', amount_gross: 10, vat_rate: 16 });
ok(r.status === 422, 'Ungültiger Steuersatz abgelehnt');
fd = new FormData();
fd.append('file', pdf, 'Beleg Ringlicht.pdf');
r = await call('POST', `/portal/expenses/${expId}/receipt`, fd, { form: true });
ok(r.status === 201, 'Beleg zur Ausgabe hochgeladen');
r = await call('PUT', '/portal/profile', { tax_buffer_rate: 25 });
ok(r.status === 200, 'Steuerpuffer eingestellt');
r = await call('GET', `/portal/finance?year=${yr}`);
ok(r.data.expenses.net === 146.73 && r.data.expenses.reimbursable_open === 50 && r.data.buffer.rate === 25, 'Ausgaben netto, offene Erstattung, Pufferrate');

// Exporte
res = await call('GET', `/portal/export/income.csv?year=${yr}`, null, { raw: true });
let tt = await res.text();
ok(res.status === 200 && tt.includes('Portal Brand') && tt.includes('800,00'), 'Export Einnahmen CSV');
res = await call('GET', `/portal/export/expenses.csv?year=${yr}&month=${Number(today.slice(5, 7))}`, null, { raw: true });
tt = await res.text();
ok(res.status === 200 && tt.includes('Ringlicht') && tt.includes('Beleg Ringlicht.pdf'), 'Export Ausgaben CSV (Monat)');
res = await call('GET', `/portal/export/datev.csv?year=${yr}&expense=4930&berater=1234567&mandant=12345`, null, { raw: true });
tt = Buffer.from(await res.arrayBuffer()).toString('latin1');
ok(res.status === 200 && tt.startsWith('"EXTF";700;21;"Buchungsstapel"') && tt.includes(';4930;1200;9;') && tt.includes('1234567;12345'), 'DATEV-Export mit eigenen Konten');
res = await call('GET', `/portal/export/package.zip?year=${yr}`, null, { raw: true });
const zipBuf = Buffer.from(await res.arrayBuffer());
ok(res.status === 200 && zipBuf.readUInt32LE(0) === 0x04034b50 && zipBuf.includes(Buffer.from('Uebersicht.txt')) && zipBuf.includes(Buffer.from('Belege/Belege/')), 'Steuerberater-Paket (ZIP mit Belegen)');
res = await call('GET', `/portal/export/foo.csv`, null, { raw: true });
ok(res.status === 404, 'Unbekannter Export → 404');
r = await call('PUT', '/portal/profile', { iban: 'DE00 1234' });
ok(r.status === 422 && r.data.details.iban, 'Ungültige IBAN abgelehnt');
r = await call('PUT', '/portal/profile', { iban: 'DE89 3704 0044 0532 0130 00', billing_street: 'Musterweg 1', billing_zip: '10115', billing_city: 'Berlin', small_business: true, size_shoes: '42', notes: 'darf nicht', status: 'Archiviert' });
ok(r.status === 200, 'Creator speichert eigene Daten');

cookie = adminC;
// Team: Creator-Ansicht (Vorschau, nur lesend)
const asTom = { 'X-View-As-Creator': String(tom) };
res = await fetch(BASE + '/portal/overview', { headers: { cookie, 'X-Requested-With': 'crm', ...asTom } });
let j = await res.json();
ok(res.status === 200 && j.preview === true && j.creator.id === tom, 'Team öffnet Creator-Ansicht');
res = await fetch(BASE + `/portal/finance?year=${yr}&as=${tom}`, { headers: { cookie, 'X-Requested-With': 'crm' } });
j = await res.json();
ok(res.status === 200 && j.expenses.net === 146.73, 'Vorschau per ?as= liefert dieselben Finanzen');
res = await fetch(BASE + '/portal/calendar', { method: 'POST', headers: { cookie, 'X-Requested-With': 'crm', 'Content-Type': 'application/json', ...asTom }, body: JSON.stringify({ entry_date: today, title: 'x' }) });
ok(res.status === 403, 'Vorschau ist schreibgeschützt');
r = await call('GET', '/portal/overview');
ok(r.status === 400, 'Team ohne Creator-Angabe → 400');
r = await call('GET', `/collaborations/${pColl}/messages`);
ok(r.data.items.length === 1 && r.data.items[0].from_creator === true, 'Team sieht Creator-Nachricht');
r = await call('POST', `/collaborations/${pColl}/messages`, { body: 'Ja, passt!' });
ok(r.status === 201, 'Team antwortet am Deal');
r = await call('GET', `/creators/${tom}/expenses`);
ok(r.data.items[0].id === reimbId && r.data.items[0].reimbursement_status === 'Beantragt', 'Team sieht beantragte Erstattung zuerst');
r = await call('PATCH', `/creator-expenses/${reimbId}`, { reimbursement_status: 'Erstattet' });
ok(r.status === 200, 'Team markiert Erstattung');
cookie = creatorC;
r = await call('DELETE', `/portal/expenses/${reimbId}`);
ok(r.status === 404, 'Erstattete Ausgabe nicht löschbar');
r = await call('DELETE', `/portal/calendar/${entryId}`);
ok(r.status === 200, 'Eigener Kalendereintrag gelöscht');
cookie = adminC;

console.log('Listen');
r = await call('POST', '/lists', { name: 'Food-Marken Mannheim', color: 'green' });
ok(r.status === 201 && r.data.list.contact_count === 0, 'Liste angelegt');
const listId = r.data.list.id;
r = await call('POST', '/lists', { name: '' });
ok(r.status === 422, 'Listenname Pflicht');
r = await call('POST', `/lists/${listId}/contacts`, { company: 'Matcha Bar', name: 'Jana Beispiel', position: 'Marketing', email: 'jana@matcha.example', city: 'Mannheim' });
ok(r.status === 201, 'Kontakt angelegt');
const contactId = r.data.contact.id;
r = await call('POST', `/lists/${listId}/contacts`, { position: 'nur Position' });
ok(r.status === 422, 'Firma oder Name nötig');
r = await call('POST', `/lists/${listId}/contacts`, { company: 'X', email: 'kaputt' });
ok(r.status === 422, 'Ungültige E-Mail abgelehnt');
r = await call('PATCH', `/list-contacts/${contactId}`, { status: 'Kontaktiert', last_contacted_on: today });
ok(r.status === 200 && r.data.contact.status === 'Kontaktiert', 'Kontaktstatus geändert');
r = await call('POST', `/lists/${listId}/import`, { csv: 'Firma;Ansprechpartner;E-Mail;Ort\nAcai Haus;Ben;ben@acai.example;Heidelberg\n"Gelato; Co";;;Mannheim\nKaputt;X;nicht-mail;' });
ok(r.status === 200 && r.data.imported === 2 && r.data.errors.length === 1, 'CSV-Import (2 ok, 1 Fehler)');
r = await call('GET', `/lists/${listId}?q=heidelberg`);
ok(r.data.contacts.length === 1 && r.data.contacts[0].company === 'Acai Haus', 'Suche in Liste');
r = await call('GET', `/lists/${listId}?status=Kontaktiert`);
ok(r.data.contacts.length === 1, 'Statusfilter');
res = await call('GET', `/lists/${listId}/export.csv`, null, { raw: true });
tt = await res.text();
ok(res.status === 200 && tt.includes('"Gelato; Co"') && tt.includes('Matcha Bar'), 'CSV-Export der Liste');
r = await call('GET', '/lists');
ok(r.data.lists[0].contact_count === 3, 'Listenübersicht mit Anzahl');
r = await call('DELETE', `/list-contacts/${contactId}`);
ok(r.status === 200, 'Kontakt entfernt');

r = await call('GET', `/creators/${tom}`);
ok(r.data.creator.iban === 'DE89370400440532013000' && r.data.creator.small_business === true && r.data.creator.status !== 'Archiviert', 'Team sieht Bankdaten, Status unverändert');
r = await call('GET', `/tasks?creator_id=${tom}`);
ok(r.data.items.some((t) => t.title === 'Content prüfen: Portal Brand'), 'Team bekommt Aufgabe zur Content-Prüfung');
r = await call('GET', `/documents?creator_id=${tom}`);
ok(r.data.items.some((d) => d.uploaded_by_creator && d.visible_to_creator), 'Team sieht Upload des Creators');
r = await call('PATCH', `/creators/${tom}/portal`, { is_active: false });
ok(r.status === 200 && r.data.access.is_active === false, 'Team sperrt Zugang');
cookie = creatorC;
r = await call('GET', '/portal/overview');
ok(r.status === 401, 'Gesperrter Creator sofort abgemeldet');
cookie = adminC;
r = await call('POST', `/creators/${tom}/portal`, {});
ok(r.status === 200 && r.data.access.is_active === true && r.data.link, 'Neue Einladung schaltet wieder frei (Passwort-Reset)');

console.log('Archivieren & Löschen');
r = await call('PATCH', `/creators/${tom}`, { status: 'Archiviert' });
r = await call('GET', '/creators');
ok(!r.data.items.some((c) => c.id === tom), 'Archivierter Creator nicht in aktiver Liste');
r = await call('GET', '/creators?archived=only');
ok(r.data.items.length === 1 && r.data.items[0].id === tom, 'Aber über Archiv-Filter auffindbar');
r = await call('DELETE', `/creators/${anna}`);
ok(r.status === 200, 'Endgültig gelöscht (Admin)');
r = await call('GET', `/documents/${docId}/file`, null, { raw: true });
ok(r.status === 404, 'Zugehörige Dateien mitgelöscht');
r = await call('GET', '/collaborations?creator_id=' + anna);
ok(r.data.total === 0, 'Kooperationen kaskadierend gelöscht');

console.log('Demo-Daten');
r = await call('POST', '/admin/seed-demo');
ok(r.status === 409, 'Demo-Daten nur in leere DB');

console.log(fails ? `\n${fails} FEHLER` : '\nAlle Tests bestanden.');
process.exit(fails ? 1 : 0);
